sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BC6o3PwFXkr10JoX6+jvi1o/Sz3qvDTswjkitK3/U8TgUcQq08VonmuYuzKv7p5P2uCGQpbyjWGp0QXFeVlosfC5Y5/xzv+CDzH5RYT3/HsfMqJ/8t4fJPwfU/s0YitAFTYSZnZaiL6ZAvTQ+h0N7TZC4Mw+M6b8fCMBcXT1U12dxTtYgCWe2oIWC1W5sVBjaJuVjUnwj7AEeBlYNBIJmlXXfltrLh2lfdN882DiiCU5zPBlmHBIW2/AqO6CJGkZsmHRkGKld2zAT/zf+Y1TG6cjin29cVo92qXiCO5AxqDelNOCL1LB6WyH8sWOOpL2S1kS8WtbbFM+CIsjz+ZNAs/43o7SL6F4kGNORtoiD8Mi2nHb/REiGR9Lx6EpK3C0Rxt39PHzvsKuB2XTcMygsLrGAxYwrnfLIhQvA3j8RiiOXgIVslB5lKrARV4Yx0W4SGehR9J0LTs9QD+SfrKaBjhKXeEs/DV4tWt7EI+V9aobJT3vrRx60GPyDMu5RzzBc67owAYMJYs8x0qnqWkTvRquSNofBA0VjptAJY71/ia1AYhgNWuV1gxsXtklOA+s/FIWLOmT061F7luj+DlG+N0rs3bb0YO1TKVvDRAqUaiIJEm1lxYfk/bQlB1kTAJp4cQ8mZvykh+qHrh5f1DQSUgW1mR7gjPhgzdDXy4S4qk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/State-of-the-Union-Addresses_5026
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy